baseURL = 'http://www.devoneriksen.com/'
languageCode = 'en-us'
title = 'Devon Eriksen'
theme = ['custom-arcana']


[params]
    [[params.social]]
        title = "Reddit"
        icon = "fa-reddit"
        url = "https://reddit.com/user/devoneriksenwrites"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook"
        url = "https://www.facebook.com/profile.php?id=100094477455578"
    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/Devon_Eriksen_"
    [[params.social]]
        title = "Mastodon"
        icon = "fa-mastodon"
        url = "https://mastodon.social/@DevonEriksen"
